### ISSUE TITLE
Create Layouts

### ISSUE THREAD

**Issue by jdittrich** [BauhausUniversity/MedienWiki#9]
Before we create a new skin (Issue #2) we need to create Layouts and test them. 
This should be done by @jdittrich together with @Giuca 
### The following usecases are assumed:
- Edit a page
- Upload an image and use it subsequently (or vice versa)
- Find a specific page
### Goals:
- Provide a layout that supports the common usecases well (aka should perform well in usability test) 
- makes the needed Elements for accomplishing the usecases easy to find
  ### Non Goals
- Create a non-opinionated structure in which everything is equally important and looks the same
- Totally hide elements that a (sub-) group of technically inexperienced people might need for their common tasks
### Todos
- [x] Research Different Layouts
- [x] Create alternative Layouts as suggestions
- [ ] Refine by researching what the common usecases for students are in order to make the necessary places easy to find and use
- [ ] Test Layouts with experienced people and newbies. Sampling pro tip: For the latter you could e.g. use design faculty or media philosophy members, who afaik don't have a wiki or that stuff in teaching

**Comment by jdittrich** [comment]
![Wikipage_Layout1_2013-04-26 11:08:19](https://f.cloud.github.com/assets/3416487/429752/0091f026-ae51-11e2-99f2-7ab47d099032.png)
First suggestion.

**Comment by jdittrich** [comment]
Zum Vergleich: Wikipedia Default
![Bildschirmfoto vom 2013-04-27 12:20:09](https://f.cloud.github.com/assets/3416487/434203/44439984-af26-11e2-8057-b92656995141.png)

**Comment by jdittrich** [comment]
Rechts oben "aufräumen"?
![Bildschirmfoto vom 2013-04-27 12:24:56](https://f.cloud.github.com/assets/3416487/434204/5b8fd42c-af26-11e2-953e-405d30b07a3d.png)

**Comment by jdittrich** [comment]
Einen Link für Hilfe in die linke obere Ecke? In http://bit.ly/HL93v als Standard erforscht; habe es in letzter Zeit aber selten gesehen; vllcht. eher die Hilfe am/im Editor ein wichtigeres Thema.  
![Bildschirmfoto vom 2013-04-27 12:22:01](https://f.cloud.github.com/assets/3416487/434205/6c7c26f0-af26-11e2-9f6c-ea02cb7c3a09.png)

**Comment by jdittrich** [comment]
![layouts2](https://f.cloud.github.com/assets/3416487/446269/07b5dcee-b1d2-11e2-9fbe-eedacf9048b0.png)

**Comment by jdittrich** [comment]
![screenshot from 2013-05-27 12 36 42](https://f.cloud.github.com/assets/3416487/567550/5a26ed28-c6b9-11e2-87f8-0585eeb5ec70.png)

ADAPTATIONS TOWARDS www.uni-weimar.de LAYOUT AND APPEARANCE

1) The gray bar was already existing on the buw website, so I incorporated it.
2) The buw page features a box-on-ground layout. This is rather inflexible. What I would suggest is maintaining the box-on-ground appearance by a padding between the main part and the gray bar and possibly by padding
between the article and the menu.
3) If we adapt horizontal Menus like the original page, we are probably in trouble. (very limited number of items)  So I kept the vertical here.
4) We might want to move often needed, always present items up in the menu.
5) Behind the arrow: Links to faculty of media and university of weimar. The Main Logo must link to the medienwiki startpage, otherwise we introduce a (really well verified) usability bug.
